/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://www.maths.calculation.site',
  generateRobotsTxt: true, // (optional)
  generateIndexSitemap: false, // This will prevent splitting into sitemap-0.xml
  additionalPaths: async (config) => {
    const paths = [
      '/about',
      '/algebra',
      '/algebra/guide',
      '/basic',
      '/big-number',
      '/binary',
      '/calculators',
      '/calculus',
      '/contact',
      '/desmos-matrix',
      '/destiny-matrix',
      '/diagonalize-matrix',
      '/disclaimer',
      '/distance',
      '/exponent',
      '/factor',
      '/fraction',
      '/gcf',
      '/geometry',
      '/geometry/area',
      '/geometry/circle',
      '/geometry/surface-area',
      '/geometry/volume',
      '/half-life',
      '/hex',
      '/lcm',
      '/log',
      '/matrix',
      '/matrix/calculator',
      '/percent-error',
      '/percentage',
      '/privacy-policy',
      '/pythagorean',
      '/random',
      '/ratio',
      '/right-triangle',
      '/root',
      '/rounding',
      '/rref',
      '/scientific',
      '/scientific-notation',
      '/slope',
      '/statistics',
      '/statistics/confidence-interval',
      '/statistics/mean-median-mode',
      '/statistics/permutation-combination',
      '/statistics/probability',
      '/statistics/sample-size',
      '/statistics/sequences',
      '/statistics/standard-deviation',
      '/statistics/z-score',
      '/terms-of-service',
      '/trigonometry',
      '/unit-converter',
    ];
    
    // map to the format next-sitemap expects
    return paths.map(path => ({
      loc: path,
      changefreq: 'daily',
      priority: 0.7,
      lastmod: new Date().toISOString(),
    }));
  },
}
