
import { PageHeader } from '@/components/page-header';
import RandomNumberGenerator from '@/components/calculators/random-number-generator';
import type { Metadata } from 'next';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

export const metadata: Metadata = {
    title: 'Random Number Generator',
    description: 'A powerful tool to generate random numbers, including integers and decimals with adjustable precision. Supports large numbers and multiple generations.',
};

const pageSchema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  "name": "Random Number Generator",
  "operatingSystem": "All",
  "applicationCategory": "Utilities",
  "description": "A tool to generate random numbers, including integers and decimals with adjustable precision, range, and count.",
  "url": "https://maths.calculation.site/random",
  "publisher": {
    "@type": "Organization",
    "name": "Math Calculators",
    "url": "https://maths.calculation.site"
  },
  "inLanguage": "en",
  "datePublished": "2024-07-26",
  "softwareVersion": "1.0.0"
};

const HowToUseGuide = () => (
    <Card>
        <CardHeader>
            <CardTitle>How to Use the Random Number Generators</CardTitle>
        </CardHeader>
        <CardContent className="space-y-6 text-muted-foreground">
            <div>
                <h3 className="text-xl font-semibold text-foreground">Simple Integer Generator</h3>
                 <ol className="list-decimal list-inside space-y-2 mt-2">
                    <li>Enter a "Lower Limit" and an "Upper Limit" for the range.</li>
                    <li>Click the "Generate" button.</li>
                    <li>A single random integer within that inclusive range will be displayed.</li>
                </ol>
            </div>
             <div>
                <h3 className="text-xl font-semibold text-foreground">Comprehensive Generator</h3>
                <ol className="list-decimal list-inside space-y-2 mt-2">
                    <li>Set your "Lower Limit" and "Upper Limit".</li>
                    <li>Enter how many random numbers you want to generate.</li>
                    <li>Choose whether you want "Integer" or "Decimal" results.</li>
                    <li>If you chose "Decimal," specify the number of decimal places (precision).</li>
                    <li>Click "Generate Numbers" to get a list of random numbers.</li>
                </ol>
            </div>
        </CardContent>
    </Card>
);

const EducationalContent = () => (
    <Card>
        <CardHeader>
            <CardTitle>Understanding Random Numbers</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-muted-foreground">
            <p>A <strong>random number</strong> is a number chosen from a pool of limited or unlimited numbers that has no discernible pattern for prediction. The pool of numbers is almost always independent of each other. However, the pool of numbers may follow a specific distribution. For example, the height of the students in a school tends to follow a normal distribution around the median height. If the height of a student is picked at random, the picked number has a higher chance to be closer to the median height than being classified as very tall or very short. The random number generators above assume that the numbers generated are independent of each other, and will be evenly spread across the whole range of possible values.</p>
            <p>A <strong>random number generator</strong>, like the ones above, is a device or algorithm that can generate one or many random numbers within a defined scope. Random number generators can be hardware-based or pseudo-random. Hardware-based random number generators can involve the use of dice, a coin for flipping, or many other devices.</p>
            <p>A <strong>pseudo-random number generator</strong> is an algorithm for generating a sequence of numbers whose properties approximate the properties of sequences of random numbers. Computer-based random number generators are almost always pseudo-random. The numbers generated by pseudo-random number generators are not truly random, as they are determined by an initial value (a seed). Our generators are also pseudo-random. The numbers generated are sufficient for most applications, but they should not be used for cryptographic purposes, which require true randomness.</p>
            <p>True random numbers are based on physical phenomena such as atmospheric noise, thermal noise, and other quantum phenomena. Methods that generate true random numbers also involve compensating for potential biases caused by the measurement process to ensure the output is uniformly random.</p>
        </CardContent>
    </Card>
);

const FaqSection = () => (
    <Card>
        <CardHeader>
            <CardTitle>Frequently Asked Questions</CardTitle>
        </CardHeader>
        <CardContent>
            <Accordion type="single" collapsible className="w-full">
                <AccordionItem value="item-1">
                    <AccordionTrigger>Are the numbers generated by this tool truly random?</AccordionTrigger>
                    <AccordionContent>
                        No. This tool uses a pseudo-random number generator (PRNG), which is an algorithm that creates a sequence of numbers that appears random. While these numbers are statistically random enough for most everyday purposes (like games or simulations), they are not truly random and should not be used for high-security applications like cryptography.
                    </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-2">
                    <AccordionTrigger>What is the difference between the Simple and Comprehensive generators?</AccordionTrigger>
                    <AccordionContent>
                        The **Simple Generator** is for quickly getting a single random integer. The **Comprehensive Generator** offers more control, allowing you to generate multiple numbers at once, choose between integers and decimals, and set the decimal precision.
                    </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-3">
                    <AccordionTrigger>Can I generate negative numbers?</AccordionTrigger>
                    <AccordionContent>
                        Yes. You can generate negative numbers by setting the "Lower Limit" to a negative value.
                    </AccordionContent>
                </AccordionItem>
                <AccordionItem value="item-4">
                    <AccordionTrigger>Is the range inclusive?</AccordionTrigger>
                    <AccordionContent>
                        Yes, the range is inclusive, meaning both the lower and upper limits are included as possible results.
                    </AccordionContent>
                </AccordionItem>
                 <AccordionItem value="item-5">
                    <AccordionTrigger>What happens if my lower limit is greater than my upper limit?</AccordionTrigger>
                    <AccordionContent>
                        The calculator will show an error message. The lower limit must be less than or equal to the upper limit to define a valid range.
                    </AccordionContent>
                </AccordionItem>
            </Accordion>
        </CardContent>
    </Card>
);

export default function RandomNumberPage() {
  return (
    <>
      <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(pageSchema) }}
      />
      <div className="flex flex-1 flex-col">
        <PageHeader title="Random Number Generator" />
        <main className="flex-1 p-4 md:p-6 lg:p-8">
          <div className="mx-auto max-w-2xl space-y-8">
              <section className="text-center">
                  <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
                      Random Number Generator
                  </h1>
                  <p className="mt-4 text-lg text-muted-foreground">
                      Generate random integers or decimals with customizable options.
                  </p>
              </section>
              <RandomNumberGenerator />
              <HowToUseGuide />
              <EducationalContent />
              <FaqSection />
          </div>
        </main>
      </div>
    </>
  );
}
