
import { PageHeader } from '@/components/page-header';
import RandomNumberGenerator from '@/components/calculators/random-number-generator';
import type { Metadata } from 'next';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export const metadata: Metadata = {
    title: 'Random Number Generator',
    description: 'A powerful tool to generate random numbers, including integers and decimals with adjustable precision. Supports large numbers and multiple generations.',
};

const EducationalContent = () => (
    <Card>
        <CardHeader>
            <CardTitle>Understanding Random Numbers</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-muted-foreground">
            <p>A <strong>random number</strong> is a number chosen from a pool of limited or unlimited numbers that has no discernible pattern for prediction. The pool of numbers is almost always independent of each other. However, the pool of numbers may follow a specific distribution. For example, the height of the students in a school tends to follow a normal distribution around the median height. If the height of a student is picked at random, the picked number has a higher chance to be closer to the median height than being classified as very tall or very short. The random number generators above assume that the numbers generated are independent of each other, and will be evenly spread across the whole range of possible values.</p>
            <p>A <strong>random number generator</strong>, like the ones above, is a device or algorithm that can generate one or many random numbers within a defined scope. Random number generators can be hardware-based or pseudo-random. Hardware-based random number generators can involve the use of dice, a coin for flipping, or many other devices.</p>
            <p>A <strong>pseudo-random number generator</strong> is an algorithm for generating a sequence of numbers whose properties approximate the properties of sequences of random numbers. Computer-based random number generators are almost always pseudo-random. The numbers generated by pseudo-random number generators are not truly random, as they are determined by an initial value (a seed). Our generators are also pseudo-random. The numbers generated are sufficient for most applications, but they should not be used for cryptographic purposes, which require true randomness.</p>
            <p>True random numbers are based on physical phenomena such as atmospheric noise, thermal noise, and other quantum phenomena. Methods that generate true random numbers also involve compensating for potential biases caused by the measurement process to ensure the output is uniformly random.</p>
        </CardContent>
    </Card>
);

export default function RandomNumberPage() {
  return (
    <div className="flex flex-1 flex-col">
      <PageHeader title="Random Number Generator" />
      <main className="flex-1 p-4 md:p-6 lg:p-8">
        <div className="mx-auto max-w-2xl space-y-8">
            <section className="text-center">
                <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
                    Random Number Generator
                </h1>
                <p className="mt-4 text-lg text-muted-foreground">
                    Generate random integers or decimals with customizable options.
                </p>
            </section>
            <RandomNumberGenerator />
            <EducationalContent />
        </div>
      </main>
    </div>
  );
}
